version: '3.7'

networks:
   frontend:
   backend:

services:

   webmvc:
      build: 
         context: .\src\Web\WebMvc
         dockerfile: Dockerfile
      environment: 
         - ASPNETCORE_ENVIRONMENT=Development 
         - CatalogUrl=http://catalog
      container_name: webshop
      ports:
         - "5500:80"
      networks:
         - frontend 
      depends_on:
         - catalog 

   catalog:
      build:
         context: .\src\Services\ProductCatalogApi
         dockerfile: Dockerfile
      image: shoes/catalog
      environment:
          - DatabaseServer=mssqlserver
          - DatabaseName=CatalogDb
          - DatabaseUser=sa
          - DatabaseUserPassword=ProductApi(!)
      container_name: catalogapi
      ports: 
         - "5000:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver

   mssqlserver:
      image: "mcr.microsoft.com/mssql/server:latest"
      ports: 
         - "1445:1433"

      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=ProductApi(!)
      networks:
         - backend
